[package]
name = "ok200-common"
version.workspace = true
edition.workspace = true

[dependencies]
dirs = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = "3"
serial_test = "3"

[lints]
workspace = true
